"""relationships fix

Revision ID: 56f01fce46e4
Revises: 7b5bbb61e799
Create Date: 2022-05-09 07:04:24.231948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56f01fce46e4'
down_revision = '7b5bbb61e799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('comments', sa.Column('post', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'all_users', ['author'], ['_id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post'], ['_id'])
    op.drop_column('posts', 'the_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('the_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post')
    op.drop_column('comments', 'author')
    # ### end Alembic commands ###
