"""add date

Revision ID: 90b78e02864f
Revises: f997ada241b6
Create Date: 2022-05-10 11:07:46.581811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b78e02864f'
down_revision = 'f997ada241b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('the_date', sa.DateTime(), nullable=True))
    op.add_column('posts', sa.Column('the_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'the_date')
    op.drop_column('comments', 'the_date')
    # ### end Alembic commands ###
