"""update comments

Revision ID: f997ada241b6
Revises: 56f01fce46e4
Create Date: 2022-05-09 12:18:38.419044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f997ada241b6'
down_revision = '56f01fce46e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.String(length=255), nullable=False))
    op.drop_column('comments', 'comment_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
